spring:
  application:
    name: WebApp-BookMyHotel
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/view/

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
server:
  port: 6060
  

registration-service:
  ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxAutoRetriesNextServer: 3
    MaxAutoRetries: 2

search-service:
  ribbon:
    ReadTimeout: 4000
    ConnectTimeout: 1000
    MaxAutoRetriesNextServer: 3
    MaxAutoRetries: 1

hotel-service:
  ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxAutoRetriesNextServer: 4
    MaxAutoRetries: 2  
    
booking-service:
  ribbon:
    ReadTimeout: 3000
    ConnectTimeout: 1000
    MaxAutoRetriesNextServer: 4
    MaxAutoRetries: 2

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"