spring:
  application:
    name: Registration-Service

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
       

  

server:
  port: 9001
 

bookMyHotel:
  loginService:
      name: login-service

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n"